# Generated by Django 2.2 on 2021-09-25 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budemapp', '0003_auto_20210925_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='date_of_seminar',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
    ]
