# Generated by Django 2.2 on 2021-09-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budemapp', '0004_auto_20210925_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='on_main_page',
            field=models.BooleanField(default=False, verbose_name='Ближайшие семинары'),
        ),
    ]
