# Generated by Django 2.2 on 2021-09-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budemapp', '0006_auto_20210925_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='more_info',
            field=models.CharField(blank=True, default='', max_length=3000, verbose_name='Дополнительная информация'),
        ),
    ]
