# Generated by Django 2.2 on 2021-09-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budemapp', '0007_seminar_more_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('text', models.CharField(max_length=2000, verbose_name='Автор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
