# Generated by Django 2.2 on 2021-09-26 18:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budemapp', '0008_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=2000, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='description',
            field=ckeditor.fields.RichTextField(default='', max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='more_info',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=3000, verbose_name='Дополнительная информация'),
        ),
    ]
